# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports = [
    (import (builtins.fetchTarball https://github.com/jmackie/nixos-networkmanager-profiles/archive/master.tar.gz))
  ];

  environment = {
    systemPackages = with pkgs; [
      bridge-utils
      networkmanager
      usbmuxd # iphone tethering
    ];
  };

  networking = {
    #enableIPv6 = false;
#    interfaces = {
#      "enp0s31f6" = {
#        useDHCP = true;
#      };
#    };

    # Open ports in the firewall.
    firewall = {
      enable = true;
      allowPing = true;
      allowedTCPPorts = [
        9999 # obs-studio
      ];
      allowedUDPPorts = [
        9999 # obs-studio
      ];
      # permit DHCP from VMs
      checkReversePath = false;
    };

    networkmanager = {
      enable = true;
      profiles = {
        # values derrived from /etc/NetworkManager/system-connections/*
        # generated by nmtui
        "home-wired" = {
          connection = {
            id = "home-wired";
            uuid = "cc716b00-ab4d-3266-8ccf-99b18c6f3fc9";
            type = "ethernet";
            autoconnect-priority = -999;
            interface-name = "enp0s31f6";
            permissions = "";
          };
          ipv4.method = "auto";
          ipv6.addr-gen-mode = "stable-privacy";
          ipv6.method = "auto";
        };
      };
    };
  };
}

